appname: WebKeePass
traces: 1
charset: 'UTF8'
content_type: "text/html"
template: "template_toolkit"
layout: "main"

engines:
  session:
    Simple:
      cookie_duration: 300 # the session is opened for 5 minutes
      cookie_name: "webkeepass.session"

  template:
    template_toolkit:
      ENCODING: 'utf-8'
  serializer:
    json:
      pretty: 1

plugins:
  Lexicon:
    namespace:      "WebKeePass::Lexicon"
    path:           "languages"
    auto_detect:    0
    default:        "en"
    func:           [l, _]
    session_name:   "lang"
    param_name:     "lang"
    langs:
      en:    "English"
